### ISSUE TITLE
Making the Debian 10 support official in the doc

### ISSUE THREAD

**Issue by teolemon** [zammad/zammad-documentation#111]
As it seems that Debian 10 support is there, is it time already to make it official in the Zammad documentation ?
`https://packager.io/gh/zammad/zammad/refs/stable `

**Comment by thorsteneckel** [comment]
Hi @teolemon - great catch! Absolutely, we'd love to receive a pull request for that.

**Comment by monotek** [comment]
closed by: https://github.com/zammad/zammad-documentation/pull/112
