### ISSUE TITLE
Delete users and organisation in zammad interface

### ISSUE THREAD

**Issue by Khawlamel** [zammad/zammad-documentation#120]
I want to delete count of users and organisation in zammad interface

**Comment by MrGeneration** [comment]
Sorry but this is a technical question and a feature request.
The Github Repositories are not the right palce for this.

For feature requests and technical questions, please consult the Zammad Community: https://communicate.zammad.org


Beside of that, this is a work in progress, however, it will take some time.
You can follow the following issue to learn when it will come:
https://github.com/zammad/zammad/issues/2074

Closing now

**Comment by Khawlamel** [comment]
thanks but this url https://communicate.zammad.org not is close

**Comment by MrGeneration** [comment]
Sorry I don't know what got into my fat fingers here - I meant:
https://community.zammad.org

**Comment by Khawlamel** [comment]
Thank you very much
