### ISSUE TITLE
cant clone the Docker Compose Git File

### ISSUE THREAD

**Issue by mpingu** [zammad/zammad-documentation#13]
The Steps on the Page https://docs.zammad.org/en/latest/install-docker-compose.html are not working
i am getting the following Error:

```
git clone git@github.com:zammad/zammad-docker-compose.git
Klone nach 'zammad-docker-compose' ...
The authenticity of host 'github.com (192.30.253.112)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'github.com,192.30.253.112' (RSA) to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.
```

Please make sure you have the correct access rights
and the repository exists.

when i changed the commando to
`git clone https://github.com/zammad/zammad-docker-compose.git `
it worked. Can you change the Documentation then?

**Comment by monotek** [comment]
Thanks for reporting. 
Its fixed in https://github.com/zammad/zammad-documentation/commit/41925315ad57e21b3ebd5b4c3ed040b3ba9bc5a8
