### ISSUE TITLE
Misplaced Commands in Database Configuration

### ISSUE THREAD

**Issue by itsbkm** [zammad/zammad-documentation#178]
Self Explanatory screenshot
<img width="966" alt="Screenshot 2021-05-01 at 3 46 52 PM" src="https://user-images.githubusercontent.com/17910269/116779565-9ebcff00-aa94-11eb-9273-991b3f42fcfb.png">

**Comment by MrGeneration** [comment]
You may want to read the whole command again to understand why `mysql` appears within the "postgresql" and `postgres` within the "mysql" tab.

If you have further questions, please post your technical question on the community: https://community.zammad.org

**Comment by itsbkm** [comment]
Oops my bad.
Just read the Bundle documentation
