### ISSUE TITLE
Elasticsearch server authentication configuration

### ISSUE THREAD

**Issue by bonellia** [zammad/zammad-documentation#180]
The sample [configuration file](https://github.com/zammad/zammad/blob/develop/contrib/nginx/elasticsearch.conf) has been removed on the following commit:  
https://github.com/zammad/zammad/commit/d9f4483075b077ff4d3f4aa34125335fe4c4cf16

Thus the documentation with the link below should be updated accordingly.
https://docs.zammad.org/en/latest/install/elasticsearch.html#optional-settings

**Comment by MrGeneration** [comment]
Oooof I'm so sorry for causing you extra work load.
I just realized.... basic authentication is still a valid use case (and supported by Zammad technically).

We removed sample configurations (non working :D) for nginx that would provide extra authentication layers as a proxy. 
As Elasticsearch does support authentication via x-pack natively we did not fix / replace those config samples. 
The documentation however is still valid. If you have authentication enabled these steps are required for the admin.

Again, sorry for causing you the trouble!
