### ISSUE TITLE
software requirements for package installation misleading

### ISSUE THREAD

**Issue by selyod-ka** [zammad/zammad-documentation#183]
hi!

i've installed zammd from you ubuntu packages. as you mention in the docs that there are [software requirements ](https://docs.zammad.org/en/latest/prerequisites/software.html) and in particular that ruby-2.6.6 is needed, i investigated how to install another ruby-version in my system. (rbenv/ rvm..)
after installing zammad i noticed however that you provide ruby-2.6.6, so no need for rbenv..

as far as i understand, you need to mention the ruby-requirements only for the installation from source.

**Comment by MrGeneration** [comment]
That's correct. 
A tip modal could be useful for that situation.

Thanks for pointing that out.

**Comment by MrGeneration** [comment]
This will be solved with upcoming Zammad 5.1 pushes

![image](https://user-images.githubusercontent.com/6549061/156781184-f26bb400-1a85-4f1f-b049-9f05cadba131.png)
