### ISSUE TITLE
"Add a date and time picker (pending till) for pending states" fails with Zammad 5.0

### ISSUE THREAD

**Issue by m4r71n** [zammad/zammad-documentation#201]
Today I've tried to create a new ticket state with a clean Zammad 5.0 installation but got stuck on https://docs.zammad.org/en/latest/admin/console/working-on-tickets.html#add-a-date-and-time-picker-pending-till-for-pending-states
```
> attribute.data_option[:required_if][:state_id] = Ticket::State.by_category(:pending).pluck(:id)
Traceback (most recent call last):
        1: from (irb):16
NoMethodError (undefined method `[]=' for nil:NilClass)
```
It seems that `required_if` and `shown_if` were removed with https://github.com/zammad/zammad/commit/05a471f90ddf40bbe3d7693cde3f0be7ab5a6ed4#diff-8a3ba1a45842a44af59b15a6b832f24438155a2a63da00d8f7a739007b7745f4R78 and 
https://github.com/zammad/zammad/commit/05a471f90ddf40bbe3d7693cde3f0be7ab5a6ed4#diff-8a3ba1a45842a44af59b15a6b832f24438155a2a63da00d8f7a739007b7745f4R79

**Comment by MrGeneration** [comment]
Thanks for the heads up - someone was playing tricks on me. :-)

Said documentation part is outdated as per Zammad 5.0.
Just skip the date picker part and continue normally.

Starting with Zammad 5.0 Core Workflows does handle that on the technical end.
