### ISSUE TITLE
Zammad/Elasticsearch software requirements doc

### ISSUE THREAD

**Issue by innov2e** [zammad/zammad-documentation#217]
Following zammad instructions I was installing a new environment and reading into zammad doc under [Software Requirements](https://docs.zammad.org/en/latest/prerequisites/software.html) i read:
Zammad/Elasticsearch version compatibility
For Zammad 5.0+ Elasticsearch 7.8+
I interpreted this in this way: 

if you are installing zammad 5.0 or greater version you have to use at least Elasticsearch 7.8 or greater

So I installed the last Elasticsearch release available that is 8.1.
I got errors during setup (see [this topic into zammad forum](https://community.zammad.org/t/elasticsearch-configuration-issue-sorry-another-one/8901))
I solved removing Elesticsearch, installing Elasticsearch v7.17.1 (last released for v7), reinstalling zammad.

Should be written into doc if v8.0+ are not supported? Or I did something wrong?

**Comment by MrGeneration** [comment]
7.8+ in this case expresses >=7.8.*; <8.*
I'm closing this issue as technical questions, if you need further help please consult the community.
