### ISSUE TITLE
Insufficient documentation of "links" in API

### ISSUE THREAD

**Issue by bogatkaj** [zammad/zammad-documentation#222]
Hey,

I' missing a documentation about what to send in the json-payload for the "links" API-endpoint.

In the currently available documentation there's only an example, but no info on what the "link_object_value" is.
Testing the ticket-id and number in our current instance gave me an empty response on a ticket which was linked.

Could you may update the documentation?

**Comment by ralf401** [comment]
Hi @bogatkaj 

I think we have it already documented. Please have a look (especially pre-release) at the documentation [here](https://docs.zammad.org/en/pre-release/api/ticket/links.html).
