### ISSUE TITLE
Ticket > Create: Add example for "guess:"

### ISSUE THREAD

**Issue by JPustkuchen** [zammad/zammad-documentation#240]
https://docs.zammad.org/en/latest/api/ticket/index.html#create

> Tip
> 
> 🐱‍👤 On behalf of users
> 
> If you want to create tickets on behalf other users, use the customer_id attribute. ticket.agent is mandatory for this. Use guess:{email address} to save an API call if you don’t know the users ID or want to create the user in question.

Could you please add a code example for this case below?
The text is unclear, as it could mean:
`"customer": "guess:david@example.com",`

or

`"guess": "david@example.com",`

What's correct?
Please clarify this with a clear example in the docs. Thanks :)

**Comment by MrGeneration** [comment]
I'll think of a wording solution.
I'm not going to add a full further code example.

**Comment by JPustkuchen** [comment]
Thank you very much for your super quick reply @MrGeneration ! :)

I think indeed it would be enough to add the full example in the text above like
"customer": "guess:david@example.com"
(if this is the correct implementation).

Thanks! BTW I just talked to another developer and he had the same confusion here, so I'm not the only stupid one haha ;)

**Comment by JPustkuchen** [comment]
Thank you very much @ralf401 ! :)
