### ISSUE TITLE
OTRS-Migrator video not working

### ISSUE THREAD

**Issue by YetAnotherGerrit** [zammad/zammad-documentation#258]
The migrator video of the OTRS-migration-manual is not working:
https://docs.zammad.org/en/latest/migration/otrs.html

![grafik](https://user-images.githubusercontent.com/97293098/203955966-03c2c763-0a3a-4e0d-b8a4-851a3676818f.png)

**Comment by MrGeneration** [comment]
🤷

**Comment by martini** [comment]
It's working again. Audience was not defined for this video. Seems to be a new feature on video.
