### ISSUE TITLE
Elasticsearch Ubuntu installation does not work

### ISSUE THREAD

**Issue by aMuTeX** [zammad/zammad-documentation#26]
The elasticsearch installation guide did not work for me
https://docs.zammad.org/en/latest/install-elasticsearch.html#ubuntu-16-04
-> elasticsearch-plugin was not found

With the steps described here https://askubuntu.com/questions/848173/how-to-install-elasticsearch-on-16-04-lts I got it working somehow (still, not quite sure how to check if it is running correctly).

Regards,
aMuTeX

**Comment by monotek** [comment]
Was elasticsearch installed successfully before?

**Comment by DRSchlaubi** [comment]
You must run `echo "deb https://artifacts.elastic.co/packages/5.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-5.x.list
wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -
apt-get update
apt-get install openjdk-8-jre elasticsearch
` before

**Comment by hanneshal** [comment]
Tested on fresh Ubuntu 16.04. installation  -> works
If you think this is a documentation issue, please let me know and send the parts we might missed.

**Comment by aMuTeX** [comment]
I was following your guide on a fresh Ubuntu Server 16.04 installation. The part with elasticsearch did not work initially. After I followed the instructions on askubuntu it seems to be working. At least when I enter a search term I get some results. Is there an other way to check correct installation?
