### ISSUE TITLE
Update: How to handle issues from postgresql-update

### ISSUE THREAD

**Issue by YetAnotherGerrit** [zammad/zammad-documentation#295]
When "apt upgrade" also updates psql, it might come to issues when updating Zammad because the database is unavailable. We should incorporate this in our update suggestion, either by adjusting our update path or by providing help on how to fix issues that happen because of this.

**Comment by MrGeneration** [comment]
No `postinstall.sh` should be robust enough to scream at the admin if he does this mistake.

**Comment by ralf401** [comment]
I would say the admin should know what he does while updating the system and close this issue. If you have objections, please let me know.

This applies also to other systems we depend on anyway (e.g. webserver).
