### ISSUE TITLE
Moving "install  from source, in Docker & in Vagrant" to development section

### ISSUE THREAD

**Issue by monotek** [zammad/zammad-documentation#3]
@martini 

As we have working installers for Centos, Debian, Ubuntu & Suse we could move "Install from source (generic)", "Install with Docker" & "Install with Vagrant" to the "Contributing / Development" section.

What do you think?

**Comment by martini** [comment]
yes

**Comment by martini** [comment]
Ups. "Install from source (generic)" and "Install with Docker" should be at normal install section. It's not developer related. Or what would be the reason?

**Comment by rkaldung** [comment]
Docker and Vagrant are usually developer environments. Install from source could be a regular deployment for OS where no packages are provided.

Just my 2¢

-- 
Roy Kaldung

**Comment by martini** [comment]
Ok, would be nice to have "Install from source (generic)" still there. Docker and Vagrant can be moved.

**Comment by monotek** [comment]
Ok. Will do it this way later...

**Comment by monotek** [comment]
Done
