### ISSUE TITLE
add more doc about ticket_history

### ISSUE THREAD

**Issue by sheitandard** [zammad/zammad-documentation#325]
Hi,

i am trying to get the history of many tickets and I can't find documentation on the API ticket_history
I use it now for one ticket at a time : api/v1/ticket_history/21293
I was wondering of getting the history for several tickets was possible and also if using a filter on date was possible
thanks

**Comment by ralf401** [comment]
Hi @sheitandard 

there is just this one endpoint for ticket history (the one you mentioned). So, it's not possible to get the history from more than one ticket via REST API. We have some endpoints, which are not covered in our documentation and this here is one of them.
