### ISSUE TITLE
SSO for Kerberos: eval if to replace mod-auth-kerb

### ISSUE THREAD

**Issue by YetAnotherGerrit** [zammad/zammad-documentation#338]
According to a customer, libapache2-mod-auth-kerb is not available any more for Debian 12 (at least), and he used [mod_auth_gssapi](https://github.com/gssapi/mod_auth_gssapi) instead. It might make sense to update our documentation regarding that.

mod_auth_gssapi describes itself "as a replacement for the aging mod_auth_kerb".

**Comment by MrGeneration** [comment]
`libapache2-mod-auth-kerb` is considered insecure and, I believe, not available within Buster already.
We had a discussion about this in the community as well 2 years ago I believe.

**Comment by HanSolo72** [comment]
I just got SSO running on Debian 12 and wrote my config in [this post.](https://community.zammad.org/t/sso-not-working/12033/3?u=r2d2). If you're interested I can update the SSO article with the changes for GSSAPI.

**Comment by MrGeneration** [comment]
Sorry but I have to reopen this.
The PR that has been merged looks very incomplete:
- klist is still listed in general actions but is not available on all systems but CentOS as it's no longer part of installed packages (by the doc)
- the steps need more seperation if that's the way it's supposed to be.

I'm afraid the current state in pre-release is "breaking" this page more than it's fixing.
