### ISSUE TITLE
Make sidebar headers different across documentation repos

### ISSUE THREAD

**Issue by dvuckovic** [zammad/zammad-documentation#365]
Currently, the sidebar header is very similar to all three docs:

* System documentation
  <img width="296" alt="Screenshot 2023-09-19 at 13 53 20" src="https://github.com/zammad/zammad-documentation/assets/6049445/ccc00e82-90df-4578-8e20-99fcea5ed5b8">

* User documentation
  <img width="294" alt="Screenshot 2023-09-19 at 13 53 29" src="https://github.com/zammad/zammad-documentation/assets/6049445/52213ad6-e8ad-413f-ba1d-12e069e55276">

* Admin documentation
  <img width="296" alt="Screenshot 2023-09-19 at 13 53 20" src="https://github.com/zammad/zammad-documentation/assets/6049445/ccc00e82-90df-4578-8e20-99fcea5ed5b8">

Consider making them slightly different, so the reader can immediately tell which documentation they are currently reading.
```[tasklist]
### Tasks
- [x] Align the headers with agreed documentation titles
- [x] Make logo sharper (2x image for high-density screens)
```

**Comment by dvuckovic** [comment]
@rolfschmidt @mgruner What do you think about including the full name of the docs in each sidebar? For example:

* <img width="297" alt="Screenshot 2023-09-19 at 13 57 38" src="https://github.com/zammad/zammad-documentation/assets/6049445/7d7f27a1-f862-4173-a6f8-f7858573e115">

* <img width="293" alt="Screenshot 2023-09-19 at 13 57 56" src="https://github.com/zammad/zammad-documentation/assets/6049445/1262bc79-df07-4189-ba06-69c011dfb645"> 

* <img width="295" alt="Screenshot 2023-09-19 at 13 57 51" src="https://github.com/zammad/zammad-documentation/assets/6049445/4a17005a-21c7-4496-b68e-c469ef51a59f">

Or would you prefer a shorter designation like before (i.e. `Zammad (for users)`)?

**Comment by mgruner** [comment]
Yep, sounds good. Can we make the phoenix sharp?
