### ISSUE TITLE
Key not found.

### ISSUE THREAD

**Issue by trstn70** [zammad/zammad-documentation#41]
What I do:
FROM: https://docs.zammad.org/en/latest/appendix-repo-file.html

apt-key adv --keyserver http://dl.packager.io/srv/zammad/zammad/key --recv-keys 6257DF9972462F57A20FFB2AB6D583CCBD33EEB8
Executing: /tmp/tmp.wg1FWjtcEn/gpg.1.sh --keyserver
http://dl.packager.io/srv/zammad/zammad/key
--recv-keys
6257DF9972462F57A20FFB2AB6D583CCBD33EEB8
gpg: requesting key BD33EEB8 from http server dl.packager.io
gpgkeys: no key data found for http://dl.packager.io/srv/zammad/zammad/key
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0
gpg: keyserver communications error: key not found
gpg: keyserver communications error: bad public key
gpg: keyserver receive failed: bad public key

What I expect.
The Key.

**Comment by olivergrahl** [comment]
This should work:
`wget -qO- https://dl.packager.io/srv/zammad/zammad/key | sudo apt-key add -`

(Source: https://packager.io/gh/zammad/zammad/builds/2710/install/ubuntu-16.04)
