### ISSUE TITLE
Remove MacOS installation instructions

### ISSUE THREAD

**Issue by ralf401** [zammad/zammad-documentation#424]
Documentation says that they are outdated: https://docs.zammad.org/en/latest/install/source/macos.html

Do we want to provide instructions for MacOS?

**Comment by ralf401** [comment]
@dvuckovic & @mgruner what do you think, should we cover MacOS installation instructions in the documentation? If yes, I would ask one of you to update it, as I don't have such a machine and OS :-)

**Comment by dvuckovic** [comment]
Oof, I don't see this as part of the installation manual, sorry. I vote to drop it completely.

The only use-case of running Zammad on macOS is to further develop it, in which case these instructions should be part of our developer manual (which they actually [are](https://github.com/zammad/zammad/blob/develop/doc/developer_manual/development_environment/how-to-set-up-a-development-environment.md)).
