### ISSUE TITLE
Facebook integration outdated

### ISSUE THREAD

**Issue by bafplus** [zammad/zammad-documentation#43]
Hy, it seems that the facebook integration is outdated.
It doesent reflect the current way Facebook handles the app creation.

Please update the docs.
https://docs.zammad.org/en/latest/channel-facebook.html#register-facebook-app

**Comment by thorsteneckel** [comment]
Start at: https://developers.facebook.com/apps/

![1](https://user-images.githubusercontent.com/3873515/35337432-7a7330f4-011b-11e8-9cd6-2b684fe80ca2.png)
![2](https://user-images.githubusercontent.com/3873515/35337435-7a961772-011b-11e8-8900-2d03c3f42ad1.png)
![3](https://user-images.githubusercontent.com/3873515/35337436-7ab20a7c-011b-11e8-854e-06180de725f7.png)
![4](https://user-images.githubusercontent.com/3873515/35337438-7acb6c60-011b-11e8-8e4f-8f87d0fc5ba9.png)
![5](https://user-images.githubusercontent.com/3873515/35337439-7ae4914a-011b-11e8-9f94-8180bbb117d6.png)
![6](https://user-images.githubusercontent.com/3873515/35337440-7afe397e-011b-11e8-9421-cc0e4acac13b.png)
![7](https://user-images.githubusercontent.com/3873515/35337441-7b174eaa-011b-11e8-887d-d6b9fb3d906d.png)
![8](https://user-images.githubusercontent.com/3873515/35337442-7b2eb900-011b-11e8-90aa-6c18fd9de840.png)
![9](https://user-images.githubusercontent.com/3873515/35337443-7b4cf5b4-011b-11e8-8089-32f832a8ce87.png)
![10](https://user-images.githubusercontent.com/3873515/35337445-7b7910f4-011b-11e8-8e49-7c9ff416f593.png)
![11](https://user-images.githubusercontent.com/3873515/35337446-7b953b62-011b-11e8-917c-20b848246c46.png)

[As Facebook.zip](https://github.com/zammad/zammad-documentation/files/1660137/Facebook.zip)

@KoJie - Please update the documentation accordingly.

**Comment by bafplus** [comment]
That seems to work, i wil further test this, thanks!

**Comment by bafplus** [comment]
Wall/page postings work, yet private messages dont come in. Am i missing a setting or service for it?

**Comment by thorsteneckel** [comment]
You're welcome. Thanks for the feedback. Messages are currently not supported: https://github.com/zammad/zammad/issues/269

**Comment by thorsteneckel** [comment]
Not implemented at all - yet.

**Comment by bafplus** [comment]
Any roadmap known?

**Comment by thorsteneckel** [comment]
No. We are currently working on other issues with a higher priority and functionalities required by our paying customers. However, we are happy to receive pull requests.

**Comment by MrGeneration** [comment]
Small update: Currently awaiting facebook moderation of app. If this is successfull I can check it with Zammad and update the documentation :>

**Comment by MrGeneration** [comment]
Small info: I currently plan on reorganizing the documentation, as this documentation repo is meant for system admins.

In my opinion stuff regarding administration within the WebApp should be inside admin-documentation. So actually the following issue will be the new issue where it has to be done. I'll leave this open, as this still contains needed information.
