### ISSUE TITLE
Add link to translation chapter as an alternative to the Rails command

### ISSUE THREAD

**Issue by dvuckovic** [zammad/zammad-documentation#445]
```[tasklist]
### Tasks
- [ ] Console > Working on the console > Other useful commands > Add translation
```

**Comment by mgruner** [comment]
Can we just drop this part from the documentation about adding a translation via rails? This is not needed any more.

**Comment by MrGeneration** [comment]
> Can we just drop this part from the documentation about adding a translation via rails? This is not needed any more.

No please don't. We still need it for translating manual things that are not available in Upstream. E.g. custom values or custom attributes.

**Comment by dvuckovic** [comment]
But with [the new feature](https://github.com/zammad/zammad/issues/4875) in place, this will surely not be required 🤔 I mean, it will still work, but is this something we want to continue to advertise?

**Comment by MrGeneration** [comment]
> But with https://github.com/zammad/zammad/issues/4875 in place, this will surely not be required 🤔 I mean, it will still work, but is this something we want to continue to advertise?

If a customer requests me to add a status, I'll then add it in english for translatability and hardly can request customer to use the feature. Technically I can but it will be a hickhack "y u no add it the way I wanted it".

The documentation does not only help externals, third parties but is also a documentation for internal agents. If we start fragmenting that, this will cause brain drain and bad situations. PO decision in my opinion. I won't be happy if if it's gone I'm very honest here.

**Comment by mgruner** [comment]
I disagree here. With the new feature there is no need to create records manually any more, @MrGeneration. No matter if it is  in Hosted or on premises. Therefore we should not endorse this workflow any more. That's why I want to have it out of the documentation.

If a customer wants to add a status, they can do this on their own with Zammad 6.3. And if they want to translate that status, they can also do that -- all via the UI. I don't see a need of any action on our side here.

Did I miss something?

**Comment by MrGeneration** [comment]
Then I'm wrong I guess. I don't care.

**Comment by mgruner** [comment]
It's not about us, and we don't want to do changes that harm other people in the company. But the features "custom states / priorities" and  the translation improvements were specifically implemented also to get away from the work on Support side.

So IMHO we should really change the workflows (and thus documentation) here, of course not without educating everyone about it.
