### ISSUE TITLE
Very minor doc error

### ISSUE THREAD

**Issue by morrismichaelc** [zammad/zammad-documentation#491]
Hi all,

On the small page in Admin Docs, "[https://docs.zammad.org/en/latest/admin/console/working-on-groups.html](https://docs.zammad.org/en/latest/admin/console/working-on-groups.html)", the intro to the section labeled "Find Groups" says:

> To open the rails console on the shell you have to enter the following commands.

but the following command is, "`>> Group.find_by(name: 'Users').follow_up_possible`". 

This seems like a probable copy/paste error. My suggested solution is either:

1) insert the actual command to enter the rails console, e.g., "zammad run rails c" OR
2) Change the intro to say, "To find a group by name, enter the following command:".

Not much of a contribution, but I'm new to Zammad, still working through Migration from OTRS. I'll get better :)

**Comment by MrGeneration** [comment]
The `>> ` part is supposed to tell you that you're in a different console context.

**Comment by morrismichaelc** [comment]
Oh! My bad... I've never seen a similar convention, but I did wonder at
the double ">". Thanks for explaining this. And I was excited to be able
to contribute something at all, even if minute... I'll have to try
again!!! 

MikeM 

On 2024-06-21 13:50, Marcel Herrguth wrote:

> The >> part is supposed to tell you that you're in a different console context. 
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].
> You are receiving this because you authored the thread.Message ID: ***@***.***>
 

Links:
------
[1]
https://github.com/zammad/zammad-documentation/issues/491#issuecomment-2183438578
[2]

**Comment by ralf401** [comment]
Hi @morrismichaelc, 
thanks for your hint! You are right, this sentence doesn't make that much sense. I'll fix that by removing it... The other parts of this section don't have it anyway.
