### ISSUE TITLE
Documentation for Mail channel

### ISSUE THREAD

**Issue by dmke** [zammad/zammad-documentation#5]
Regarding the Mail channel documentation, it reads

> Sorry, this still needs to be added :-(

Out of curiosity, where would one start? The ways to receive mails with an Rails application range from configuring a IMAP or POP3 client, using a Webhook for external mail services to setting up a local MTA (and, in case of Postfix, adding a transport to `/etc/postfix/master.cf`).

What is available in Zammad? Which source code do I need to read? Are there example stubs I could reuse?

**Comment by monotek** [comment]
I updated the site: https://docs.zammad.org/en/latest/channel-mail.html
Basicly its about configuring Zammad to fetch and send mails (POP3 / IMAP / SMTP).
You don't need to edit your MTA configuration.

**Comment by dmke** [comment]
I personally perfer having a local MTA for performance(*) reasons, but the IMAP client will do.

(*) I have found [`Channel::Driver::MailStdin`](https://github.com/zammad/zammad/blob/develop/app/models/channel/driver/mail_stdin.rb), but running `rails runner` for each incoming mail isn't helpful... But I can reuse [`Channel::EmailParser`](https://github.com/zammad/zammad/blob/develop/app/models/channel/email_parser.rb) to adpot a custom async runner (à la Sidekiq).
