### ISSUE TITLE
Add pnpm dependency

### ISSUE THREAD

**Issue by mgruner** [zammad/zammad-documentation#507]
With Zammad 6.4, [`pnpm`](https://pnpm.io) will be required to compile the assets. AFAICT the documentation does not mention yet that yarn was required, but for pnpm we should add a hint.

This is only relevant in cases where asset compilation must be run (source installation). Therefore I believe where we mention a manual nodejs installation in the docs we should simply add a hint to pnpm as well.

Installation methods:
- `corepack enable pnpm`
- `npm -g install pnpm` (if corepack is not available)

**Comment by mgruner** [comment]
@ralf401 is this clear enough and can you handle this, please?

**Comment by ralf401** [comment]
Yes I think it's clear, thank you for providing details!
