### ISSUE TITLE
Enhance handling of unprocessable mails for docker env

### ISSUE THREAD

**Issue by YetAnotherGerrit** [zammad/zammad-documentation#512]
We have a great documentation about the new handling of undprocessable mails. It is a pretty basic skill for Zammad admins, but hard to understand, if you are using docker. Can we please enhance that?

**Comment by MrGeneration** [comment]
I don't understand the issue to be frank. This documentation part is as "bad" equally for package installations and docker installation as it expects you to read this page first:
https://docs.zammad.org/en/latest/admin/console.html

and well this for docker users...
https://docs.zammad.org/en/latest/install/docker-compose.html#how-to-run-commands-in-the-stack

**Comment by YetAnotherGerrit** [comment]
But in docker it's not enough to just run the same command. As this will export the files to a directory within the docker container. Or this expected to be done anyway?

**Comment by MrGeneration** [comment]
> But in docker it's not enough to just run the same command. As this will export the files to a directory within the docker container. Or this expected to be done anyway?

I'd expect the administrator to qualify the mails right after exporting as in removal or another import try and push those files to a safe location that need digging. Am I expecting too much?
