### ISSUE TITLE
Add "apt-mark hold zammad" to the update suggestion

### ISSUE THREAD

**Issue by YetAnotherGerrit** [zammad/zammad-documentation#525]
Because of situations like this:
https://community.zammad.org/t/apt-get-dist-upgrade-y-can-break-your-zammad-install/15344

I suggest changing the update suggestion for debian/ubuntu on this page:
https://docs.zammad.org/en/latest/install/update.html

From this:
```bash
$ apt update
$ apt upgrade
```

To this:
```bash
$ apt update
$ apt-mark hold zammad
$ apt upgrade
$ apt-mark unhold zammad
$ apt upgrade
```

This makes sure Zammad is updated separately after upgrading of other components is done.

**Comment by rolfschmidt** [comment]
This issue should also be referenced https://github.com/zammad/zammad/issues/5309

**Comment by rolfschmidt** [comment]
Also there should be a seperate example for the **sudo apt-get dist-upgrade** as well.

**Comment by rolfschmidt** [comment]
Ah this is the right issue I think https://github.com/zammad/zammad/issues/5247

**Comment by MrGeneration** [comment]
System upgrades are hardly to cover. As our documentation currently transitions to stays out everything that's third party, this would highly apply.

**Comment by ralf401** [comment]
I agree with @MrGeneration that an `apt dist-upgrade` is a bit out of scope.

I tried to find corresponding commands (apt-mark hold) for `zypper` and `yum` as well, but could not find easy ones. I then decided to just update zammad before updating all other packages. This should help in this case too, or did I miss something? I aligned that for the other distros, too. 

Now it is for example for Ubuntu/Debian:
`apt update`
`apt upgrade zammad`
`apt upgrade`

Ok that way? Anyone wants to have a look as review or can I merge it?

**Comment by MrGeneration** [comment]
An explicit "install" command just for Zammad should™️ be good enough as well (after refreshing repos; then updating the rest). Updating especially with database server updates should be done with stopped Zammad though to be on the save side.

**Comment by ralf401** [comment]
Added it, thanks for mentioning it!

`$ apt update`
`$ apt upgrade zammad         # updating only Zammad`
`$ systemctl stop zammad      # stop Zammad`
`$ apt upgrade                # updating all packages`
`$ systemctl start zammad     # start Zammad again`

Will merge it tomorrow morning if there are no objections.

**Comment by YetAnotherGerrit** [comment]
The upgrade routine of Zammad also makes sure that the latest version of the `ingest-attachment` is installed for elasticsearch. So, if you upgrade Zammad before the rest and elasticsearch is upgraded after Zammad, elasticsearch will stop working, unless you manually fix that.

Also, we already have a `systemctl stop zammad` in our documentation on step 2 of the process. With upgrading Zammad before the rest, we need to stop Zammad twice.

All existing processes point to "upgrade everything else, upgrade Zammad afterwards".
