### ISSUE TITLE
Adjust OpenSUSE/CentOS install instructions

### ISSUE THREAD

**Issue by ralf401** [zammad/zammad-documentation#527]
- Firewall not installed by default
- Wget not installed by default
- Alignment and consistency for different distros, separation of OpenSUSE/SLES where needed
- Locale detection: replace "LC_CTYPE" with LANG
- Add local creation command if there is none

**Comment by t-shehab** [comment]
The following command is needed for `systemctl enable elasticsearch` to work:

`mv /etc/init.d/elasticsearch /etc/systemd/system/elasticsearch`
