### ISSUE TITLE
Use /etc/apt/keyring instead of trusted.gpg.d

### ISSUE THREAD

**Issue by joachimschmidt557** [zammad/zammad-documentation#538]
The instructions currently recommend installing the apt signing key into `/etc/apt/trusted.gpg.d/`:

https://github.com/zammad/zammad-documentation/blob/ce02287048bd79ab86041b8e5c3cf44ddd4d8e20/install/package.rst?plain=1#L128-L129

As explained e.g. [here](https://stackoverflow.com/a/71384057) and in general, the best practice is to install it into a different directory such as `/etc/apt/keyring/` or `/usr/share/keyrings` (e.g. [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/deb.html)). This is because keys in `trusted.gpg.d` are trusted for **all** apt repositories, not only the one that they are supposed to sign.

**Comment by ralf401** [comment]
Hi @joachimschmidt557 

thanks a lot for your hint! I change it to /etc/apt/keyrings.
