### ISSUE TITLE
Change order of installation types

### ISSUE THREAD

**Issue by ralf401** [zammad/zammad-documentation#545]
First idea:

Align it to zammad/zammad README.md repo.

Order of install types:

- Docker
- Kubernetes
- Package
- Source (not mentioned)

Update:
Currently, container based installations should not be in first place because of the lack of platform support from our side. However, source installation should be moved to the end to reflect that this is only a very advanced and barely used install method.

**Comment by ralf401** [comment]
Hi @YetAnotherGerrit & @mgruner 

as there were talks on the offsite, I changed the order in the "Installation & Update" section. Because of the not officially supported container based installations, I put it after the package installation. The order is now:

**Installation & Update**

- Package Installation
- Source Installation
- Set Up Elasticsearch
- Install with Docker
- Install on Kubernetes
- Updating Zammad

Are you ok with that? As an alternative, I could create a single "Installation" page which links to the different install types as sub pages. Then the left side bar would be much cleaner and we could put a warning / recommendation in it for the different types.

**Comment by mgruner** [comment]
I think we should consider not recommending package installation any longer, and instead point people to docker/kubernetes instead.

**Comment by YetAnotherGerrit** [comment]
I am okay with the order "Package, Source, etc.". But while you are on it. It says "Package Installation" and "Source Installation" (with "Installation" at the end), while it says "Install with Docker", "Install on Kubernetes" with "Install" at the beginning. Should we unify it?

"Install via package manager"
"Install from source"

**Comment by mgruner** [comment]
Yes, that was about "source" installation, of course.

**Comment by ralf401** [comment]
Now it looks like that:
![grafik](https://github.com/user-attachments/assets/6a94292f-7b99-4cdb-aff6-0417f85d53ac)

I merge this now. If you have objections, let me know.
