### ISSUE TITLE
API command referencing a specific ticket with its tags returns empty results with curly brackets

### ISSUE THREAD

**Issue by Suhopoljac** [zammad/zammad-documentation#557]
When listing tags via the API command, the use of curly brackets (as currently described below) displays an empty field:

https://docs.zammad.org/en/latest/api/ticket/tags.html#list
![Image](https://github.com/user-attachments/assets/c63974ee-287f-41e1-9c88-8f0fd6fc2010)

However, if you use the same link, only without curly brackets, the tags will be listed:

https://example.zammad.com/api/v1/tags?object=Ticket&o_id=317

**Comment by YetAnotherGerrit** [comment]
We use the curly brackets for placeholder all over in our documentation. This is not about this specific endpoint. I don't see an issue here.

**Comment by Suhopoljac** [comment]
Thanks for the clarification, then the issue can be closed.
