### ISSUE TITLE
OTRS-Migration Guide lacks Repository for OTRS3

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad-documentation#64]
As OTRS3 is support by our migrator (and there's actually a download available for version 3) there should also be a repository download for OTRS3. If user doesn't have this repository, he can't install the migrator-plugin successfull.

Link to documentation:
https://docs.zammad.org/en/latest/migration-otrs.html

**Comment by thorsteneckel** [comment]
The download link is: https://addons.znuny.com/api/addon_repos/public/142/latest

**Comment by MrGeneration** [comment]
Has been fixed / added.
