### ISSUE TITLE
Zammad on CentOS

### ISSUE THREAD

**Issue by caydinli** [zammad/zammad-documentation#75]
Kapitel: Install on CentOS via RPM
Die Überschriften U1 bis U3 in diesem Kapitel sind durcheinandergeraten.

Chapter: Install on CentOS via RPM
The headings U1 to U3 in this chapter are confused.
![grafik](https://user-images.githubusercontent.com/46677240/51171196-8d925900-18b0-11e9-99af-1872c9df4b02.png)

**Comment by MrGeneration** [comment]
Thanks for your hint, I'll take a look asap

**Comment by MrGeneration** [comment]
Okay, now it's live. Thanks again for the info! :)
