### ISSUE TITLE
delete user via console

### ISSUE THREAD

**Issue by KoJie** [zammad/zammad-documentation#80]
the documentation does not say something about how to delete user via Console. 
For the sake of completeness this should be added, because otherwise it is misleading if there is only information about deleting users with the help of the API.
The hint that there can be side effects should of course be included.

**Comment by MrGeneration** [comment]
The rework of the console documentation is now finished.
While I was at it, I added information on how to destroy users.

https://docs.zammad.org/en/latest/console/dangerzone-for-experts.html#delete-one-or-more-users-with-all-their-related-information

**Comment by promisepreston** [comment]
So I just figured out a way to delete objects such as **users** or **tickets** from the **database**.

Let's say you want to delete a user with the email: `johndoe@example.com`, to delete the user, follow this:

1. Open your console: `RAILS_ENV=production rails console`
2. Search for the user: `user = User.where(email: "johndoe@example.com")
This will display all the information about the user.
3. Delete the user and all related information: `user.destroy_all`

That's all.

I hope it helps.

**Comment by MrGeneration** [comment]
### Warning:
**We strongly do advise against using `.destroy_all`**

This potentially briggs your system and ecnourage you to use the above linked commands to delete one or more users. Our suggested script also provides the things it's going to delete.

Also you don't need to reindex your Searchindex, as this should be triggered by Zammad automatically.

Thanks for your time and effort. For the next time, please don't hijack old closed issues, as this is a bit troublesome for the overview :) If you have enhancements for the documentation, pull requests are very welcome!
