### ISSUE TITLE
Update Software list (ES)

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad-documentation#82]
The mandatory software list is outdated and incorrect.
Elasticsearch is optional, not mandatory.

This should be updated within documentation.

**Comment by monotek** [comment]
It should be clear that you lose functionality when ES is missing.
Not sure if this is really optional?
@martini ?

**Comment by martini** [comment]
> It should be clear that you lose functionality when ES is missing.
Not sure if this is really optional?
@martini ?

Yes, it's optional. But most installations use ES.

If you use no ES, only very limited search is possible (only one search term and slow SQL like search is used). No fast full indexed (including attachments) is possible.

**Comment by rkaldung** [comment]
> It should be clear that you lose functionality when ES is missing.
> Not sure if this is really optional?

I fully agree, ES is essential, except for the wording ;-) You don't lose anything without ES, you get something with installing it. Because it's optional.

**Comment by MrGeneration** [comment]
I'll make something up as soon as I'm ready to go.

**Comment by MrGeneration** [comment]
Documentation has been updated. We now have a small hint on where to find needed information "How do I upgrade ES", supported elasticsearch versions are complete now and also, we do no longer claim ES being required.
