### ISSUE TITLE
Push Notification for mobile app

### ISSUE THREAD

**Issue by yasinugrl** [zammad/zammad-documentation#87]
Hi all,
We can create mobile app by using this api. Can you support push notification service for IOS and Android App? 
For example when user create ticket or answer ticket, other user get the notification for this actions.

Thanks for your help.

**Comment by MrGeneration** [comment]
Sorry but I believe that this is a technical question.
Our repositories are rather a bad place for those.

I'd like to ask you to consult our community for this: https://community zammad.org

Please note that we currently can't support any push notification service. 
This would rather be a feature request (that also would want to live inside our community :) )

Closing now
