### ISSUE TITLE
High level overview of zammad.

### ISSUE THREAD

**Issue by umair-khanzada** [zammad/zammad-documentation#98]
Sorry for reaching out this way, Actually I have written an article on zammad and created a comparison table hope this gonna help you.

[Article](https://medium.com/@umairkz52/zammad-helpdesk-customer-support-system-5920578e13b4)
[Comparison table gist](https://gist.github.com/umair-khanzada/c962b5c3c023bdc777005af387f5e6de)
[Comparision table .png](https://user-images.githubusercontent.com/8782817/50981299-7a803180-151c-11e9-8dad-188c73dcaeab.png)

**Comment by MrGeneration** [comment]
Sorry, but this is not the place where such information should life. :) Next time, maybe the Community is better.

Closing.
